# Generated by Django 6.0.6 on 2026-07-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_followup_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('wishlist', 'Wishlist'), ('applied', 'Applied'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='wishlist', max_length=50),
        ),
        migrations.AlterField(
            model_name='applicationstatushistory',
            name='status',
            field=models.CharField(choices=[('wishlist', 'Wishlist'), ('applied', 'Applied'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], max_length=50),
        ),
    ]
