# Generated by Django 6.0.6 on 2026-07-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_auto_delete_exports_user_export_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reminder_lead_time',
            field=models.IntegerField(default=3),
        ),
    ]
