# Generated by Django 6.0.6 on 2026-07-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_reminder_lead_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reminder_lead_time',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
