# Generated by Django 6.0.6 on 2026-07-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_emailchangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='locale',
            field=models.CharField(choices=[('af', 'Afrikaans'), ('ig', 'Asụsụ Ìgbò'), ('en-au', 'Australian English'), ('az', 'Azərbaycanca'), ('id', 'Bahasa Indonesia'), ('ms', 'Bahasa Melayu'), ('eu', 'Basque'), ('en-gb', 'British English'), ('cy', 'Cymraeg'), ('de', 'Deutsch'), ('en', 'English'), ('eo', 'Esperanto'), ('ga', 'Gaeilge'), ('gd', 'Gàidhlig'), ('hr', 'Hrvatski'), ('ia', 'Interlingua'), ('kn', 'Kannada'), ('km', 'Khmer'), ('sw', 'Kiswahili'), ('ht', 'Kreyòl Ayisyen'), ('lt', 'Lietuviškai'), ('lb', 'Lëtzebuergesch'), ('hu', 'Magyar'), ('mn', 'Mongolian'), ('nl', 'Nederlands'), ('pt', 'Português'), ('pt-br', 'Português Brasileiro'), ('pa', 'Punjabi'), ('ro', 'Română'), ('sl', 'Slovenščina'), ('vi', 'Tiếng Việt'), ('tk', 'Türkmençe'), ('tr', 'Türkçe'), ('ast', 'asturianu'), ('bs', 'bosanski'), ('br', 'brezhoneg'), ('ca', 'català'), ('da', 'dansk'), ('dsb', 'dolnoserbski'), ('et', 'eesti'), ('es', 'español'), ('es-ar', 'español de Argentina'), ('es-co', 'español de Colombia'), ('es-mx', 'español de Mexico'), ('es-ni', 'español de Nicaragua'), ('es-ve', 'español de Venezuela'), ('fr', 'français'), ('fy', 'frysk'), ('gl', 'galego'), ('hsb', 'hornjoserbsce'), ('io', 'ido'), ('it', 'italiano'), ('lv', 'latviešu'), ('no', 'norsk'), ('nb', 'norsk (bokmål)'), ('nn', 'norsk (nynorsk)'), ('uz', 'oʻzbek tili'), ('pl', 'polski'), ('sq', 'shqip'), ('sk', 'slovensky'), ('sr-latn', 'srpski (latinica)'), ('fi', 'suomi'), ('sv', 'svenska'), ('kab', 'taqbaylit'), ('is', 'Íslenska'), ('cs', 'česky'), ('el', 'Ελληνικά'), ('os', 'Ирон'), ('ky', 'Кыргызча'), ('mk', 'Македонски'), ('ru', 'Русский'), ('tt', 'Татарча'), ('udm', 'Удмурт'), ('uk', 'Українська'), ('be', 'беларуская'), ('bg', 'български'), ('sr', 'српски'), ('tg', 'тоҷикӣ'), ('kk', 'Қазақ'), ('hy', 'հայերեն'), ('he', 'עברית'), ('ug', 'ئۇيغۇرچە'), ('ur', 'اردو'), ('ar-dz', 'العربية الجزائرية'), ('ar', 'العربيّة'), ('fa', 'فارسی'), ('ckb', 'کوردی'), ('ne', 'नेपाली'), ('mr', 'मराठी'), ('hi', 'हिंदी'), ('bn', 'বাংলা'), ('ta', 'தமிழ்'), ('te', 'తెలుగు'), ('ml', 'മലയാളം'), ('th', 'ภาษาไทย'), ('my', 'မြန်မာဘာသာ'), ('ka', 'ქართული'), ('ja', '日本語'), ('zh-hans', '简体中文'), ('zh-hant', '繁體中文'), ('ko', '한국어')], default='en', max_length=20),
        ),
    ]
