# Generated by Django 6.0.6 on 2026-07-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_locale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=20),
        ),
    ]
