# Generated by Django 6.0.6 on 2026-07-09 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0005_followup_completed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('phone', 'Phone'), ('video', 'Video'), ('onsite', 'On-site'), ('take_home', 'Take-home Assignment'), ('other', 'Other')], max_length=20)),
                ('round_name', models.CharField(max_length=100)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('meeting_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.application')),
            ],
        ),
    ]
